---
apiVersion: v1
kind: Service
metadata:
  name: app2-svc
  labels:
    app: app2-svc
spec:
  type: ClusterIP
  selector:
    run: app2
  ports:
  - name: rule1
    port: 80
    protocol: TCP
    targetPort: 80
